services:
  frontend:
    image: subicura/guestbook-frontend:latest
    ports:
      - "80:80"
    environment:
      - PORT=80
      - GUESTBOOK_API_ADDR=backend:8000
    depends_on:
      - backend

  backend:
    image: subicura/guestbook-backend:latest
    environment:
      - PORT=8000
      - GUESTBOOK_DB_ADDR=mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4
    volumes:
      - guestbook-db:/data/db

volumes:
  guestbook-db:
